name: anidb
on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  anidb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: withsiren/datasets/anidb@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
